### ISSUE TITLE
Create basic issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/IssueScanner#1]
Create a basic issue template to be used for other issues in this project.

Refer to **Velaptor** to get issue template.

**Issue Dependencies**

- KinsonDigital/issues-repo#9

**Comment by kselena** [comment]
Is this issue needed anymore @CalvinWilkinson ?

**Comment by kselena** [comment]
@CalvinWilkinson  is this issue still needed?  I don't believe it is since the issue templates were moved to .github repo.

**Comment by CalvinWilkinson** [comment]
No.  This issue is not required anymore as the direction on how templates are managed have not changed.

Closed issue.
